export const SAVE_RESPONSE_CORRECT = "@@QUESTION/SAVE_RESPONSE_CORRECT";
export const SAVE_RESPONSE_CORRECT_FAIL = "@@QUESTION/SAVE_RESPONSE_CORRECT_FAIL";
export const SAVE_RESPONSE_CORRECT_SUCCESS = "@@QUESTION/SAVE_RESPONSE_CORRECT_SUCCESS";

export const SAVE_RESPONSE_INCORRECT = "@@QUESTION/SAVE_RESPONSE_INCORRECT";
export const SAVE_RESPONSE_INCORRECT_FAIL = "@@QUESTION/SAVE_RESPONSE_INCORRECT_FAIL";
export const SAVE_RESPONSE_INCORRECT_SUCCESS = "@@QUESTION/SAVE_RESPONSE_INCORRECT_SUCCESS";

export const SAVE_NAME = "@@QUESTION/SAVE_NAME";
export const SAVE_NAME_FAIL = "@@QUESTION/SAVE_NAME_FAIL";
export const SAVE_NAME_SUCCESS = "@@QUESTION/SAVE_NAME_SUCCESS";

export const FINISH = "FINISH_QUIZ";