export const SAVE_RESPONSE = "@@QUESTION/SAVE_RESPONSE";

export const SAVE_NAME = "@@QUESTION/SAVE_NAME";
export const SAVE_NAME_FAIL = "@@QUESTION/SAVE_NAME_FAIL";
export const SAVE_NAME_SUCCESS = "@@QUESTION/SAVE_NAME_SUCCESS";